# This is a basic workflow to help you get started with Actions

name: Test
on:
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Codespaces Key Sync
        uses: shellerci/codespace-keys@test
        with:
          pat: ${{ secrets.CS_KEYS_PAT }}
          organization: customink
